- package-lock.json
- package.json
- src/components/common/DataTable.tsx
- src/components/common/ErrorMessage.tsx
- src/components/common/LoadingSpinner.tsx
- src/components/projects/ProjectCard.tsx
- src/components/projects/ProjectHeader.tsx
- src/components/projects/ProjectStages.tsx
- src/components/projects/StageCard.tsx
- src/main.tsx
- src/pages/admin/projects/Project.tsx
- src/pages/admin/projects/ProjectList.tsx
- src/pages/auth/Login.tsx
- src/pages/user/projects/UserProject.tsx
- src/services/projectService.ts
- src/stores/projectStore.ts
- src/types/project.ts
- src/types/stage.ts
- src/types/task.ts
- src/utils/dateUtils.ts
프로젝트 관련 조회 API 연동하였습니다.
#5 
- 관리자 페이지에서 전체 프로젝트 리스트 조회 API 연동했습니다.
- 관리자 페이지에서 해당 프로젝트 정보 조회 API 연동했습니다.
- 프로젝트 페이지에서 프로젝트 정보 / 단계 / task 조회 API 연동했습니다.
> [Feature] 프로젝트 조회 API 연동

- src/api/axios.ts
- src/api/config.ts
- src/api/project.ts
- src/api/task.ts
- src/components/projects/AddStageModal.tsx
- src/components/projects/AddTaskModal.tsx
- src/components/projects/ProjectStages.tsx
- src/components/projects/StageCard.tsx
- src/components/projects/TaskRequestsModal.tsx
- src/components/tasks/Task.tsx
- src/pages/projects/[id]/index.tsx
- src/types/api.ts
- src/types/project.ts
- src/types/stage.ts
프로젝트 상세 페이지 내 단계(Stage) 및 작업(Task) 관리 기능을 구현하고 관련 API를 연동했습니다.
*   **프로젝트 상세 페이지 라우팅 추가:** `src/pages/projects/[id]/index.tsx` 경로 추가 및 기본 구조 구현.
*   **단계(Stage) 관리:**
*   `getProjectStages` API 연동하여 단계 및 하위 작업 목록 표시 (`ProjectStages.tsx`).
*   단계 순서 변경을 위한 드래그 앤 드롭 기능 구현.
*   단계 추가/수정 UI 컴포넌트 (`StageCard`, `AddStageModal`) 구현 (API 연동 추후).
*   **작업(Task) 관리:**
*   `StageCard` 내 작업 목록 표시 및 순서 변경 드래그 앤 드롭 구현.
*   작업 추가 UI 컴포넌트 (`AddTaskModal`) 구현 (API 연동 추후).
*   작업 클릭 시 `getTaskRequests` API 연동하여 요청 목록 조회 및 모달(`TaskRequestsModal`) 표시.
*   **API 설정 및 연동:**
*   중앙 Axios 인스턴스(`axios.ts`) 설정 및 요청 시 토큰 자동 첨부 인터셉터 추가.
*   단계/작업 관련 API 함수(`project.ts`, `task.ts`) 및 엔드포인트(`config.ts`) 추가.
*   관련 TypeScript 타입 정의 (`api.ts`, `project.ts`, `stage.ts`).
#12
> Feature/stagetask #12

- build.sh
배포를 위한 파일을 추가했습니다. (팀 레포에서 개인 레포로 복사하는 역할)
> setting: build.sh 파일 추가

- src/components/calendar/SimpleCalendar.tsx
- src/components/projects/StageCard.tsx
- src/pages/admin/projects/Project.tsx
- src/services/projectService.ts
- src/types/project.ts
vercel 배포시 발생했던 오류를 해결하기 위해 일부 코드를 수정했습니다.
#17 
- 필요 없는 Import 삭제
- type 오류 해결
> [Fix] build 오류 해결

- src/components/layout/UserSidebar.tsx
- src/components/projects/ProjectArticle.tsx
- src/types/article.ts
배포 후 확인할 때 생긴 버그를 수정하기 위해 API 연동을 추가로 진행하였습니다.
#26 
- 유저/관리자 모두 볼 수 있는 프로젝트 메인 페이지 접속 시 사이드바 변경
- ADMIN인 경우 전체 프로젝트 목록 조회 API 연동
- USER인 경우 해당 사용자가 참여 중인 프로젝트 목록 조회 API 연동
- 게시글 삭제 오류 해결
- 게시글 삭제된 경우에 따라 다르도록 API 수정 후 다시 연동
- [백엔드 PR 참고](https://github.com/Kernel360/KDEV4-SODA-BE/issues/105)
> [Feature] 기타 API 연동

- src/components/layout/Header.tsx
- vercel.json
vercel 배포 후 생긴 새로고침 오류 해결
#39 
- `versel.json` 추가
> [Fix] vercel 새로고침 오류 해결

- src/components/projects/PaymentManagement.tsx
- 프로젝트 상세 대시보드에서 단계별 요청수가 출력이 되는데, 현재 위치한 단계가 아니면 0건으로 조회되는 단계별 요청수가 0건으로 출력되는 버그 해결하였습니다.
Closed #71
> [Fix] 단계별 요청수 제대로 출력되게 수정

- src/api/config.ts
- 백엔드 요청엔드포인트 수정
- 로컬 백엔드 서버 -> 배포한 ec2 백엔드 서버 
Closed #79
> chore: 백엔드 엔드포인트 수정

- src/pages/admin/AdminMain.tsx
- src/services/projectService.ts
> [Bug] 로그인시 오류 해결

- src/api/config.ts
- src/pages/admin/AdminMain.tsx
- src/services/projectService.ts
> [Release] Develop to Main

- src/pages/user/projects/RequestDetail.tsx
- 승인요청에 대한 응답들이 조회되지 않는 버그 해결
#120 
- [Fix] 프로젝트 상세페이지에서 승인요청이 조회되지 않는 버그 해결 #119
위 PR과 동일한 이유(Request의 parentId가 -1인 경우 처리 로직의 부재)로 승인응답이 조회되지 않는 버그가 있어 parentId==-1일 때 처리로직을 추가하여 해결함
> [Fix] parentId가 -1일 경우 승인요청에 대한 응답들 조회되지 않는 버그 해결

- src/api/axios.ts
- src/api/config.ts
- src/components/articles/ArticleForm.tsx
- src/pages/article/EditArticle.tsx
- src/pages/user/projects/CreateRequest.tsx
- src/pages/user/projects/RequestDetail.tsx
- src/services/commentService.ts
- src/services/projectService.ts
- presigned Url 발급 받고 S3에 직접 파일 저장하고 백엔드에 확인 메세지 보내게 구현
#107 
- 게시글, 승인요청, 승인응답 모두에 적용하였습니다.
- 자세한 내용은 BE PR을 참고해주세요
- https://github.com/Kernel360/KDEV4-SODA-BE/pull/214
> [Feature] presigned Url 발급 받고 S3에 직접 파일 저장하고 백엔드에 확인 메세지 보내게 구현

- src/api/axios.ts
- src/api/config.ts
- src/pages/admin/AdminMain.tsx
- src/services/commentService.ts
- src/services/projectService.ts
- 어드민 대시보드의 진행중인 프로젝트에서 대시보드 버튼을 눌렀을 때 프로젝트 상세 수정페이지로 넘어가는 버그 해결
Closed #131
> [Fix] 어드민 대시보드의 진행중인 프로젝트에서 대시보드 버튼을 눌렀을 때 프로젝트 상세 수정페이지로 넘어가는 버그 해결

- src/pages/user/UserDashboard.tsx
- 유저 대시보드에서 최근 승인요청 목록 기능 구현
Closed #112
> [Feat] 유저 대시보드에서 최근 승인요청 목록 기능 구현

- src/components/comments/CommentSection.tsx
게시글 대댓글 버튼이 사라지고 삭제가 안되는 오류를 해결했습니다.
#159 
- 대댓글 버튼 추가
- 삭제 오류 수정
> [Fix] 게시글 대댓글 오류 해결

- package-lock.json
- package.json
- src/components/charts/CompanyCreationTrendChart.tsx
- src/components/charts/ProjectCreationTrendChart.tsx
- src/pages/admin/AdminMain.tsx
- src/pages/user/UserMain.tsx
- src/services/projectService.ts
프로젝트/회사 생성 통계 API 연동
#142 
1. 프로젝트 생성 통계 API 연동
2. 회사 생성 통계 API 연동
> [Feature] 프로젝트/회사 생성 통계 API 연동

- src/components/projects/PaymentManagement.tsx
- 재승인요청이 승인요청과 그루핑되어 가장 위에 복제 출력되는 버그 수정
#177
- 백엔드쪽에서 생성일 기준으로 정렬 + 재승인요청은 부모요청 바로 아래에 순서 위치시키게 데이터 반환되게 만들어 프론트는 그냥 그걸 출력하는 것으로 로직 수정하였습니다.
> [Fix] 재승인요청이 승인요청과 그루핑되어 가장 위에 복제 출력되는 버그 수정

- src/api/auth.ts
- src/components/projects/CreateProjectSteps.tsx
- src/components/projects/ProjectHeader.tsx
- src/pages/admin/projects/Project.tsx
- src/pages/user/MyArticles.tsx
- src/pages/user/UserDashboard.tsx
프로젝트 관련 오류 해결
#175 
- 프로젝트 생성 관련 오류 해결
- 멤버 추가 오류 해결
- 프로젝트 대시보드에서 단계 수정만 가능하도록 제한 (담당자만 가능)
- 초기 프로필 세팅 연동 오류 해결
> [Fix] 프로젝트 관련 오류 해결

- src/components/projects/PaymentManagement.tsx
- src/components/projects/ProjectArticle.tsx
- src/components/projects/ProjectHeader.tsx
- src/services/projectService.ts
디자인 일부 수정
#182 
- 단계 관리 모달로 수정
- 질문관리 탭 우선순위/상태별 조회 필터링 추가
- 승인관리 탭 상태별 조회 추가
> [Design] 프로젝트 관련 디자인 수정

- src/pages/user/projects/RequestDetail.tsx
- 재승인요청에서 부모요청 버튼 눌렀을 때 이동되게 수정
#194
> [Fix] 재승인요청에서 부모요청 버튼 눌렀을 때 이동되게 수정

- src/api/admin.ts
- src/services/noticeService.ts
api 주소 변경으로 인한 오류 수정 했습니다.
- 좋은 예시) feat : 깃허브 로그인 버튼 컴포넌트 구현 (#13)
- 나쁜 예시) feat : 로그인 구현
> [Bug] api 주소 변경으로 인한 오류 수정

- src/pages/article/EditArticle.tsx
- src/services/projectService.ts
게시글 API 연동 오류 해결
#209 
- 게시글 수정 시 단계 수정 안되는 오류 해결
- 게시글 수정 시 투표 생성 안되는 오류 해결
> [Fix] 게시글 API 연동 오류 해결

- src/components/layout/Header.tsx
- src/pages/admin/projects/Project.tsx
- src/pages/auth/Login.tsx
- src/pages/user/projects/CreateRequest.tsx
- presignedUrl 업로드 시 ACL 읽기 설정 추가
#211
> [Feat] presignedUrl 업로드 시 ACL 읽기 설정 추가

- src/pages/user/projects/CreateRequest.tsx
> [Fix] acm설정 삭제

- src/components/layout/Header.tsx
- src/components/layout/Layout.tsx
- src/components/layout/Sidebar.tsx
- src/components/layout/UserSidebar.tsx
- src/pages/admin/AdminMain.tsx
- src/pages/user/UserDashboard.tsx
관리자 대시보드, 사용자 대시보드 반응형 추가
#223 
- 관리자로 로그인 시 나오는 `관리자 대시보드` 모바일 화면 추가
- 사용자로 로그인 시 나오는 `사용자 대시보드` 모바일 화면 추가
- Header 반응형 적용
> [Design] 관리자 대시보드, 사용자 대시보드 모바일 반응형 적용

- src/components/comments/CommentSection.tsx
- src/pages/admin/AdminMain.tsx
- src/pages/article/Article.tsx
- src/pages/user/UserDashboard.tsx
- src/pages/user/UserRequests.tsx
- src/pages/user/projects/RequestDetail.tsx
대시보드 디자인 오류 수정 및 createdAt 한국 시간으로 설정
#226
> [Design] 대시보드 디자인 오류 수정 및 createdAt 한국 시간으로 설정

- src/pages/user/projects/CreateRequest.tsx
> [Fix] 불필요한 코드 삭제

- src/pages/auth/UserInfo.tsx
> [Bug] 유저 초기정보 등록 수정

- src/pages/admin/DataManagement.tsx
- 상세보기했을 때 데이터 보이게 분기문 삭제
#234
> [Fix] 상세보기했을 때 데이터 보이게 분기문 삭제

- src/pages/admin/DataManagement.tsx
- src/pages/auth/UserInfo.tsx
> Develop to main

- src/api/auth.ts
- src/api/client.ts
- src/api/config.ts
- src/components/layout/Header.tsx
- src/contexts/ToastContext.tsx
- src/pages/admin/accounts/AccountDetail.tsx
- src/pages/auth/FindId.tsx
- src/pages/auth/FindPassword.tsx
- src/pages/auth/Login.tsx
- src/pages/auth/UserInfo.tsx
- src/services/authService.ts
- src/services/memberService.ts
- src/stores/userStore.ts
- src/types/api.ts
- src/types/member.ts
멤버 상태를 추가하고
아이디 찾기, 비밀번호찾기 기능에서 문제를 발견해 수정했습니다
#233
> 멤버 상태 추가, 푸론트 오류수정
